export const POPULATE_DISCUSSION = "DUSCUSSION.POPULATE";
export const ADD_DISCUSSION = "DUSCUSSION.ADD";
export const UPDATE_DISCUSSION = "DUSCUSSION.UPDATE";
export const REMOVE_DISCUSSION = "DUSCUSSION.REMOVE";